<?php
$web_message[0] = "Please login first!!";
$web_message[1] = "Game maintenance, please try again later...";
$web_message[2] = "Parameter error...";
$web_message[3] = "An error occurred...";
$web_message[4] = "Binding failed! Do not use a postal account";
$web_message[5] = "Not yet logged in";
$web_message[6] = "System is busy";
$web_message[7] = "You have applied, please wait for opening";
$web_message[8] = "Defocal Account Repetition";
$web_message[9] = "No account parameters";
$web_message[10] = "You have already received";
$web_message[11] = "The system cannot find a member";
$web_message[12] = "Gift failed";
$web_message[13] = "You have already received";
$web_message[14] = "You have applied for it, no need to repeat the application";
$web_message[15] = "Cannot find this item";
$web_message[16] = "This item has been removed or not yet available";
$web_message[17] = "Your bonus points are insufficient";
$web_message[18] = "This bonus item is out of stock and the redemption failed";
$web_message[19] = "Gift to"; //After picking up the name
$web_message[20] = "This item has been redeemed";
$web_message[21] = "The phone number you entered does not match";
$web_message[22] = "You have already received it and cannot receive it again.";
$web_message[23] = "This serial number could not be found";
$web_message[24] = "This serial number has been redeemed";
$web_message[25] = "No data found";
$web_message[26] = "Please browse with your phone!";
$web_message[27] = "Send failed!!";
$web_message[28] = "Members can only sell once on the same day!! Please re-sell on the next day";
$web_message[29] = "Non-VIP members are only allowed to sell twice a week!! Please resell them every other week";
$web_message[30] = "Insufficient balance,";
$web_message[31] = "Your balance is less than the withdrawal limit"; //The number of contacts behind
$web_message[32] = "Because you have a withdrawal limit, you can only withdraw the maximum"; //The number of contacts behind
$web_message[33] = "Phone verification failed";
$web_message[34] = "Send success!!";
$web_message[35] = "Test environment, this feature is not supported!";
$web_message[36] = "Failed to enter!!";
$web_message[37] = "Please login again";
$web_message[38] = "The pavilion you selected is still being solved and cannot be transferred to";
$web_message[39] = "You are a credit member and cannot transfer to this venue";
$web_message[40] = "(You may not have logged in to Obo, please do the first login before performing the transfer action)";
$web_message[41] = "When you participate in the 91 Howard, you will not be able to enter the Ou Bo real estate game for the time being, please \"update the balance\" Ou Bo Pavilion, export your points \"quick transfer\" To the wallet."; //This sentence can not be turned
$web_message[42] = "The pavilion of your choice, currently does not open the mission";
$web_message[43] = "Transfer to success!!";
$web_message[44] = "Failed out!!";
$web_message[45] = "The pavilion you selected is still being solved and cannot be transferred at this time";
$web_message[46] = "You are a credit member and cannot transfer points from this library";
$web_message[47] = "Your credit line is currently being resolved and cannot be transferred out of this library";
$web_message[48] = "Insufficient balance, failed to fetch";
$web_message[49] = "Please log in to Texas Hold'em for the first turn";
$web_message[50] = "Transfer successfully!!";
$web_message[51] = "Send successfully, and will be served by customer service at a later time";
$web_message[52] = "Update successful";
$web_message[53] = "[Under review]";
$web_message[54] = "[Apply Agent]";
$web_message[55] = "Sorry! The system could not find your information!!";
$web_message[56] = "Sorry! You have verified, no need to verify again!!";
$web_message[57] = "Sorry! You verified the error!!";
$web_message[58] = "Mobile verification succeeded!!";
$web_message[59] = "You are a credit member, you cannot operate this project, please contact customer service!!";
$web_message[60] = "The permission function is insufficient, please contact customer service staff!!";
$web_message[61] = "Sorry, because you participated in the first reserve activity, the primary account is locked, and the function can only be performed after the solution!!";
$web_message[62] = "The account or password is incorrect!!";
$web_message[63] = "This account has been registered!!";
$web_message[64] = "Your account is currently being deactivated by the administrator!!";
$web_message[65] = "Registration Verification Code";
$web_message[66] = "Maintenance!";
$web_message[67] = "Registered successfully!!";
$web_message[68] = "Want to jump to the home page";
$web_message[69] = "Verification Error";
$web_message[70] = "Time verification expired!!";
$web_message[71] = "Scratch verification has expired, please log in again!;";
$web_message[72] = "Login failed!!";
$web_message[73] = "The Zalo account is incorrect!!";
$web_message[74] = "This bank account has been used, please contact customer service";
$web_message[75] = "This bank account has been locked, please contact customer service";
$web_message[76] = " In maintenance";
$web_message[77] = " Periodic maintenance：";


$a_status = array("0" =>"Applied",
                  "1" =>"Handling",
				  "2" =>"Finished",
				  "4" =>"Insufficient Balance",
				  "99"=>"Cancel");
				  
$a_action = array("withdraw_back"=>"Return withdrawal",
                  "deposit"      =>"Deposit",
				  "withdraw"     =>"Withdrawal",
				  "tran"         =>"Transfer",
				  "backwater"    =>"Cash Back",);


$game_name['allbet'] ='ALLBET'; 	//歐博
$game_name['salong'] ='SALONG'; 	//沙龍
$game_name['salong2']='SALONG';		//新沙龍
$game_name['ugs']	 ='UG'; 		//UG
$game_name['bbin']	 ='BBIN'; 		//bbin
$game_name['cq9']	 ='CQ9'; 		//CQ9
$game_name['qtech']	 ='Qtech'; 		//QTech
$game_name['cfb']	 ='CFB'; 		//鬥雞
$game_name['dg']	 ='DG'; 		//DG
$game_name['vsl']	 ='VSL'; 		//VSL越南彩
$game_name['fish']	 ='GG FISH'; 	//GG捕魚
$game_name['wm'] 	 ='WM'; 		//WM
$game_name['sexy']	 ='SEXY'; 		//sexy
$game_name['igs']	 ='IGSlot'; 	//IGSlot
$game_name['CMD']	 ='CMD'; 		//CMD
$game_name['SEA']	 ='SEA'; 		//SEA
$game_name['V8']	 ='V8'; 		//V8
$game_name['FAST']	 ='FAST'; 		//FAST
$game_name['RICH']	 ='RICH'; 		//RICH
$game_name['MS']	 ='MS'; 		//MS
$game_name['IM']	 ='IM'; 		//IM
$game_name['saba']	 ='SABA'; 		//SABA
$game_name['ASG']	 ='AG'; 		//ASG
$game_name['EBET']	 ='EBET'; 		//EBET
?>