<?php
$web_message[0] = "請先登入會員!!";
$web_message[1] = "遊戲維護中，請稍後再試...";
$web_message[2] = "參數錯誤...";
$web_message[3] = "發生錯誤...";
$web_message[4] = "綁定失敗！請勿使用郵政帳號";
$web_message[5] = "尚未登入";
$web_message[6] = "系統忙碌中";
$web_message[7] = "您已申請，請等待開通";
$web_message[8] = "德撲圈帳號重覆";
$web_message[9] = "無帳號參數";
$web_message[10] = "您已領過";
$web_message[11] = "系統找不到會員";
$web_message[12] = "贈送失敗";
$web_message[13] = "您已領過";
$web_message[14] = "您已申請過，無須重覆申請";
$web_message[15] = "找不到此商品";
$web_message[16] = "此商品已下架或尚未上架";
$web_message[17] = "您的紅利點數不足";
$web_message[18] = "此紅利商品已無庫存，兌換失敗";
$web_message[19] = "贈送給"; //後面接人名
$web_message[20] = "此商品已被兌換";
$web_message[21] = "您所輸入的手機號碼不符";
$web_message[22] = "您已領取過，不得重覆領取。";
$web_message[23] = "找不到此序號";
$web_message[24] = "此序號已被兌換";
$web_message[25] = "找不到資料";
$web_message[26] = "請用手機瀏覽!";
$web_message[27] = "送出失敗!!";
$web_message[28] = "會員當日託售僅限定一次!!請您於隔日再進行託售";
$web_message[29] = "非VIP會員每週託售僅限定兩次!!請您於隔週再進行託售";
$web_message[30] = "餘額不足，";
$web_message[31] = "您的餘額少於提領限制"; //後面接點數
$web_message[32] = "由於您有提領限制，最大只能提領";	//後面接點數
$web_message[33] = "手機驗證失敗";
$web_message[34] = "送出成功!!";
$web_message[35] = "測試環境，不支援此功能!";
$web_message[36] = "轉入失敗!!";
$web_message[37] = "請重新登入";
$web_message[38] = "您所選擇的館別尚在解涷中，目前無法轉入";
$web_message[39] = "您為信用會員，無法轉點到此館";
$web_message[40] = "（您可能尚未登入過歐博遊戲，請先做第一次登入後，再執行轉入動作）";
$web_message[41] = "參與91豪客賽期間，您將暫時無法進入歐博真人館遊戲，請先\"更新餘額\"歐博館，將您的點數\"快速轉帳\"匯出至錢包。"; //此句可不翻
$web_message[42] = "您所選擇的館別，目前不開放解涷任務";
$web_message[43] = "轉入成功!!";
$web_message[44] = "轉出失敗!!";
$web_message[45] = "您所選擇的館別尚在解涷中，目前無法轉出";
$web_message[46] = "您為信用會員，無法將點數由此館轉出";
$web_message[47] = "您的信用額度目前在解定中，無法將點數由此館轉出";
$web_message[48] = "餘額不足，取出失敗";
$web_message[49] = "第一次轉點請先登入過德州撲克";
$web_message[50] = "轉出成功!!";
$web_message[51] = "送出成功，稍後由客服人服為您服務";
$web_message[52] = "更新成功";
$web_message[53] = "[審核中]";
$web_message[54] = "[申請代理]";
$web_message[55] = "很抱歉！系統找不到您的資料!!";
$web_message[56] = "很抱歉！您已驗證通過，無須再次驗證!!";
$web_message[57] = "很抱歉！您驗證錯誤!!";
$web_message[58] = "手機驗證成功!!";
$web_message[59] = "您為信用會員，無法操作此項目，請洽客服人員!!";
$web_message[60] = "權限功能不足，請洽客服人員!!";
$web_message[61] = "很抱歉，因為您參加了首儲活動，主帳被鎖定中，解涷後才能進行此功能!!";
$web_message[62] = "帳號或密碼錯誤!!";
$web_message[63] = "此帳號已被註冊過!!";
$web_message[64] = "您的帳號目前被管理者停用中!!";
$web_message[65] = "註冊驗證碼";
$web_message[66] = "維護中!";
$web_message[67] = "註冊成功!!";
$web_message[68] = "即將跳轉至首頁";
$web_message[69] = "驗證錯誤";
$web_message[70] = "時間驗證過期!!";
$web_message[71] = "暫存驗證已過期，請重新登入!;";
$web_message[72] = "登入失敗!!";
$web_message[73] = "此Zalo帳號已被註冊過!!";
$web_message[74] = "此銀行帳號已被綁定，請聯繫客服";
$web_message[75] = "此銀行帳號已被鎖定，請聯繫客服";
$web_message[76] = " 維護中";
$web_message[77] = " 定期維護：";


$a_status = array("0" =>"已申請",
                  "1" =>"處理中",
				  "2" =>"已完成",
				  "4" =>"餘額不足",
				  "99"=>"取消");

$a_action = array("withdraw_back"=>"提款退回",
                  "deposit"      =>"存款",
				  "withdraw"     =>"提款",
				  "tran"         =>"轉帳",
				  "backwater"    =>"返水",);


$game_name['allbet'] ='歐博';
$game_name['salong'] ='沙龍';
$game_name['salong2']='沙龍';
$game_name['ugs']    ='UG';
$game_name['bbin']   ='BBIN';
$game_name['cq9']    ='CQ9'; 
$game_name['qtech']  ='QTech';
$game_name['cfb']    ='鬥雞';
$game_name['dg']     ='DG';
$game_name['vsl']	 ='VSL越南彩';
$game_name['fish']	 ='GG捕魚';
$game_name['wm']	 ='WM';
$game_name['sexy']	 ='SEXY';
$game_name['igs']	 ='IGSlot';
$game_name['CMD']	 ='CMD';
$game_name['SEA']	 ='SEA';
$game_name['V8']	 ='V8';
$game_name['FAST']	 ='FAST';
$game_name['RICH']	 ='RICH';
$game_name['MS']	 ='MS';
$game_name['IM']	 ='IM';
$game_name['saba']	 ='SABA';
$game_name['ASG']	 ='AG';
$game_name['EBET']	 ='EBET';
?>