<?php
$web_message[0] = "Vui lòng đăng nhập hội viên!!";
$web_message[1] = "Trò chơi đang bảo trì, vui lòng thử lại sau...";
$web_message[2] = "Số liệu sai...";
$web_message[3] = "Xuất hiện lỗi...";
$web_message[4] = "Liên kết thất bại, vui lòng không sử dụng tài khoản bưu điện";
$web_message[5] = "Chưa đăng nhập";
$web_message[6] = "Hệ thống đang bận";
$web_message[7] = "Bạn đã đề nghị, vui lòng đợi mở";
$web_message[8] = "Tài khoản PokerMaster bị trùng";
$web_message[9] = "Không có dữ liệu tài khoản";
$web_message[10] = "Bạn đã từng nhận";
$web_message[11] = "Hệ thống không tìm thấy hội viên";
$web_message[12] = "Gửi tặng thất bại";
$web_message[13] = "Bạn đã từng nhận";
$web_message[14] = "Bạn đã từng đề nghị, vui lòng không lặp lại đề nghị";
$web_message[15] = "Tìm không thấy sản phẩm này";
$web_message[16] = "Sản phẩm này đã bị gỡ xuống hoặc chưa đưa lên";
$web_message[17] = "Điểm thưởng của bạn không đủ··";
$web_message[18] = "Sản phẩm thưởng này đã hết hàng, đổi thất bại";
$web_message[19] = "Tặng quà cho"; //後面接人名
$web_message[20] = "Sản phẩm này đã được đổi";
$web_message[21] = "Số điện thoại bạn đã nhập không khớp";
$web_message[22] = "Bạn đã từng nhận, không được lặp lại.";
$web_message[23] = "Tìm không thấy số sê-ri này";
$web_message[24] = "Số sê-ri này đã được đổi";
$web_message[25] = "Tìm không thấy dữ liệu";
$web_message[26] = "Vui lòng kiểm tra điện thoại!";
$web_message[27] = "Gửi đi thất bại!!";
$web_message[28] = "Hội viên trong ngày chỉ có thể rút tiền một lần!! vui lòng tiếp tục rút tiền vào ngày kế tiếp";
$web_message[29] = "Không phải hội viên VIP mỗi tuần chỉ có thể rút tiền hai lần, vui lòng rút tiền vào tuần kế tiếp";
$web_message[30] = "Số dư không đủ，";
$web_message[31] = "Số dư của bạn nhỏ hơn hạn mức rút tiền thấp nhất"; //後面接點數
$web_message[32] = "Do bạn có hạn mức rút tiền, nhiều nhất chỉ có thể rút";	//後面接點數
$web_message[33] = "Xác minh điện thoại thất bại";
$web_message[34] = "Gửi đi thành công!!";
$web_message[35] = "Môi trường thử nghiệm, không ủng hộ chức năng này!!";
$web_message[36] = "Chuyển điểm thất bại!!";
$web_message[37] = "Vui lòng đăng nhập lại";
$web_message[38] = "Trò chơi bạn lựa chọn đang đóng băng, trước mắt không thể chuyển điểm vào";
$web_message[39] = "Bạn là hội viên tín dụng, không thể chuyển điểm đến trò chơi này";
$web_message[40] = "（Có thể bạn chưa từng đăng nhập game allbet, vui lòng đăng nhập lần đầu, sau đó mới chuyển điểm ra）";
$web_message[41] = "Trong thời gian tham gia giải đấu Poker 91, bạn tạm thời không thể tham gia allbet live, vui lòng vào mục cấp nhật số dư -> allbet game-> điểm số ->chuyển nhanh -> chọn chuyển đến ví tiền của bạn。"; //此句可不翻
$web_message[42] = "Trò chơi bạn lựa chọn trước mắt không mở nhiệm vụ giải phóng";
$web_message[43] = "Chuyển điểm thành công!!";
$web_message[44] = "Chuyển điểm thất bại!!";
$web_message[45] = "Trò chơi bạn lựa chọn đang đóng băng, trước mắt không thể chuyển điểm ra";
$web_message[46] = "Bạn là hội viên tín dụng, không thể chuyển điểm từ trò chơi này";
$web_message[47] = "Mức độ tín dụng của bạn đang được quyết định, không thể chuyển điểm từ trò chơi này";
$web_message[48] = "Số dư không đủ, rút tiền thất bại";
$web_message[49] = "Lần đầu tiên chuyển điểm vui lòng đăng nhập Texas Hold'em";
$web_message[50] = "Chuyển điểm thành công!!";
$web_message[51] = "Gửi đi thành công, một lúc sau sẽ có nhân viên chăm sóc khách hàng phục vụ bạn ";
$web_message[52] = "Cập nhật thành công";
$web_message[53] = "[Đang xét duyệt]";
$web_message[54] = "[Ủy quyền]";
$web_message[55] = "Rất xin lỗi, tìm không thấy dữ liệu của bạn!!";
$web_message[56] = "Rất xin lỗi, xác minh đã hết hạn, không thể tiếp tục sử dụng!!";
$web_message[57] = "Rất xin lỗi, Xác minh sai!!";
$web_message[58] = "Xác minh điện thoại thành công!!";
$web_message[59] = "Bạn là hội viên tín dụng, không thể sử dụng mục này, vui lòng liên hệ nhân viên chăm sóc khách hàng!!";
$web_message[60] = "Không đủ quyền hạn, vui lòng liên hệ nhân viên chăm sóc khách hàng!!";
$web_message[61] = "Rất xin lỗi, do bạn đã tham gia khuyến mãi nạp tiền lần đầu, nên tài khoản chính đang bị khóa, sau khi được giải phóng mới có thể sử dụng chức năng này!!";
$web_message[62] = "Tài khoản hoặc mật khẩu sai!!";
$web_message[63] = "Tài khoản này đã được đăng ký!!";
$web_message[64] = "Tài khoản của bạn trước mắt đang bị ban quản lý đình chỉ!!";
$web_message[65] = "Mã xác minh đăng ký";
$web_message[66] = "Đang bảo trì!!";
$web_message[67] = "Đăng ký thành công!!";
$web_message[68] = "Đang chuyển đến trang chủ";
$web_message[69] = "Xác minh sai";
$web_message[70] = "Hết thời gian xác minh!!";
$web_message[71] = "Xác minh tạm lưu đã hết hạn, vui lòng đăng nhập lại!!";
$web_message[72] = "Đăng nhập thành công··!!";
$web_message[73] = "Số điện thoại đã đăng ký";

$a_status = array("0"=>"Đã yêu cầu",
                  "1"=>"Đang xử lý",
				  "2"=>"Hoàn tất",
				  "4"=>"Số dư không đủ",
				  "99"=>"Huỷ");
				  
$a_action = array("withdraw_back"=>"Yêu cầu bị từ chối",
                  "deposit"=>"Nạp tiền",
				  "withdraw"=>"Rút tiền",
				  "tran"=>"Chuyển quỹ",
				  "backwater"=>"Hoàn trả",);
?>