<?php
$web_message[0] = "请先登入会员!!";
$web_message[1] = "游戏维护中，请稍后再试...";
$web_message[2] = "参数错误...";
$web_message[3] = "发生错误...";
$web_message[4] = "绑定失败！请勿使用邮政帐号";
$web_message[5] = "尚未登入";
$web_message[6] = "系统忙碌中";
$web_message[7] = "您已申请，请等待开通";
$web_message[8] = "德扑圈帐号重覆";
$web_message[9] = "无帐号参数";
$web_message[10] = "您已领过";
$web_message[11] = "系统找不到会员";
$web_message[12] = "赠送失败";
$web_message[13] = "您已领过";
$web_message[14] = "您已申请过，无须重覆申请";
$web_message[15] = "找不到此商品";
$web_message[16] = "此商品已下架或尚未上架";
$web_message[17] = "您的红利点数不足";
$web_message[18] = "此红利商品已无库存，兑换失败";
$web_message[19] = "赠送给"; //后面接人名
$web_message[20] = "此商品已被兑换";
$web_message[21] = "您所输入的手机号码不符";
$web_message[22] = "您已领取过，不得重覆领取。";
$web_message[23] = "找不到此序号";
$web_message[24] = "此序号已被兑换";
$web_message[25] = "找不到资料";
$web_message[26] = "请用手机浏览!";
$web_message[27] = "送出失败!!";
$web_message[28] = "会员当日托售仅限定一次!!请您于隔日再进行托售";
$web_message[29] = "非VIP会员每周托售仅限定两次!!请您于隔周再进行托售";
$web_message[30] = "余额不足，";
$web_message[31] = "您的余额少于提领限制"; //后面接点数
$web_message[32] = "由于您有提领限制，最大只能提领";	//后面接点数
$web_message[33] = "手机验证失败";
$web_message[34] = "送出成功!!";
$web_message[35] = "测试环境，不支援此功能!";
$web_message[36] = "转入失败!!";
$web_message[37] = "请重新登入";
$web_message[38] = "您所选择的馆别尚在解涷中，目前无法转入";
$web_message[39] = "您为信用会员，无法转点到此馆";
$web_message[40] = "（您可能尚未登入过欧博游戏，请先做第一次登入后，再执行转入动作）";
$web_message[41] = "参与91豪客赛期间，您将暂时无法进入欧博真人馆游戏，请先\"更新余额\"欧博馆，将您的点数\"快速转帐\"汇出至钱包。"; //此句可不翻
$web_message[42] = "您所选择的馆别，目前不开放解涷任务";
$web_message[43] = "转入成功!!";
$web_message[44] = "转出失败!!";
$web_message[45] = "您所选择的馆别尚在解涷中，目前无法转出";
$web_message[46] = "您为信用会员，无法将点数由此馆转出";
$web_message[47] = "您的信用额度目前在解定中，无法将点数由此馆转出";
$web_message[48] = "余额不足，取出失败";
$web_message[49] = "第一次转点请先登入过德州扑克";
$web_message[50] = "转出成功!!";
$web_message[51] = "送出成功，稍后由客服人服为您服务";
$web_message[52] = "更新成功";
$web_message[53] = "[审核中]";
$web_message[54] = "[申请代理]";
$web_message[55] = "很抱歉！系统找不到您的资料!!";
$web_message[56] = "很抱歉！您已验证通过，无须再次验证!!";
$web_message[57] = "很抱歉！您验证错误!!";
$web_message[58] = "手机验证成功!!";
$web_message[59] = "您为信用会员，无法操作此项目，请洽客服人员!!";
$web_message[60] = "权限功能不足，请洽客服人员!!";
$web_message[61] = "很抱歉，因为您参加了首储活动，主帐被锁定中，解涷后才能进行此功能!!";
$web_message[62] = "帐号或密码错误!!";
$web_message[63] = "此帐号已被注册过!!";
$web_message[64] = "您的帐号目前被管理者停用中!!";
$web_message[65] = "注册验证码";
$web_message[66] = "维护中!";
$web_message[67] = "注册成功!!";
$web_message[68] = "即将跳转至首页";
$web_message[69] = "验证错误";
$web_message[70] = "时间验证过期!!";
$web_message[71] = "暂存验证已过期，请重新登入!;";
$web_message[72] = "登入失败!!";
$web_message[73] = "此Zalo帐号已被注册过!!";
$web_message[74] = "此銀行帳號已被綁定，請聯繫客服";
$web_message[75] = "此銀行帳號已被鎖定，請聯繫客服";
$web_message[76] = " 維護中";
$web_message[77] = " 定期維護：";


$a_status = array("0" =>"已申请",
                  "1" =>"处理中",
				  "2" =>"已完成",
				  "4" =>"余额不足",
				  "99"=>"取消");
				  
$a_action = array("withdraw_back"=>"提款退回",
                  "deposit"      =>"存款",
				  "withdraw"     =>"提款",
				  "tran"         =>"转帐",
				  "backwater"    =>"返水",);


$game_name['allbet'] ='歐博';
$game_name['salong'] ='沙龍';
$game_name['salong2']='沙龍';
$game_name['ugs']    ='UG';
$game_name['bbin']   ='BBIN';
$game_name['cq9']    ='CQ9'; 
$game_name['qtech']  ='QTech';
$game_name['cfb']    ='鬥雞';
$game_name['dg']     ='DG';
$game_name['vsl']	 ='VSL越南彩';
$game_name['fish']	 ='GG捕魚';
$game_name['wm']	 ='WM';
$game_name['sexy']	 ='SEXY';
$game_name['igs']	 ='IGSlot';
$game_name['CMD']	 ='CMD';
$game_name['SEA']	 ='SEA';
$game_name['V8']	 ='V8';
$game_name['FAST']	 ='FAST';
$game_name['RICH']	 ='RICH';
$game_name['MS']	 ='MS';
$game_name['IM']	 ='IM';
$game_name['saba']	 ='SABA';
$game_name['ASG']	 ='AG';
$game_name['EBET']	 ='EBET';
?>